### ISSUE TITLE
Does not play nicely with the 'bare' template on which it was built.

### ISSUE THREAD

**Issue by ghost** [BlackrockDigital/startbootstrap-1-col-portfolio#2]
If you assemble this with the bare template as the nav menu suggests it was built on, there is a noticeable jump by ~8 px right on the whole page.  I haven't found the cause yet, but I know it lies in how each project item (row) is floated.  When you only have a single row, this issue goes away.  I will post if I figure it out.

**Comment by davidtmiller** [comment]
Should be fixed in BS4 build.
